export const API_FAMILIES = {
  LinearRegression: "Regression",
  PolynomialRegression: "Regression",
  RidgeRegression: "Regression",
  LassoRegression: "Regression",
  ElasticNet: "Regression",
  WeightedRegression: "Regression",
  RobustRegression: "Regression",
  LogisticRegression: "Classification",
  MulticlassLogisticRegression: "Classification",
  KNearestNeighbors: "Classification",
  NeuralNetwork: "Classification",
  Matrix: "Matrix",
  residualDiagnostics: "Diagnostics",
  studentizedResiduals: "Diagnostics",
  cooksDistance: "Diagnostics",
  leverage: "Diagnostics",
  durbinWatson: "Diagnostics",
  breuschPagan: "Diagnostics",
  shapiroWilk: "Diagnostics",
  vif: "Diagnostics",
  correlationMatrix: "Diagnostics",
  conditionNumber: "Diagnostics",
  confidenceInterval: "Intervals",
  predictionInterval: "Intervals",
  bootstrapCoefficients: "Intervals",
  standardize: "Preprocessing",
  unstandardize: "Preprocessing",
  normalize: "Preprocessing",
  unnormalize: "Preprocessing",
  oneHotEncode: "Preprocessing",
  polynomialFeatures: "Preprocessing",
  interactionFeatures: "Preprocessing",
  dropMissing: "Preprocessing",
  imputeMean: "Preprocessing",
  imputeMedian: "Preprocessing",
  isWasmActive: "Runtime",
} as const;

export const METHOD_COVERAGE = {
  LinearRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "residuals",
    "statistics",
    "summary",
  ],
  PolynomialRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "residuals",
    "statistics",
    "summary",
  ],
  RidgeRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "residuals",
    "statistics",
    "summary",
  ],
  LassoRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "residuals",
    "statistics",
    "summary",
  ],
  ElasticNet: ["coefficients", "intercept", "fit", "predict", "residuals", "statistics", "summary"],
  WeightedRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "residuals",
    "statistics",
    "summary",
  ],
  RobustRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "residuals",
    "statistics",
    "summary",
  ],
  LogisticRegression: [
    "coefficients",
    "intercept",
    "fit",
    "predict",
    "predictProbability",
    "statistics",
  ],
  MulticlassLogisticRegression: [
    "weights",
    "classes",
    "fit",
    "predict",
    "predictProbability",
    "statistics",
  ],
  KNearestNeighbors: ["fit", "predict", "neighbors"],
  NeuralNetwork: ["fit", "predict", "predictRaw"],
  Matrix: [
    "fromArray",
    "zeros",
    "ones",
    "identity",
    "columnVector",
    "rowVector",
    "diagonal",
    "get",
    "set",
    "getColumn",
    "getRow",
    "setColumn",
    "transpose",
    "multiply",
    "add",
    "subtract",
    "scale",
    "addInPlace",
    "subtractInPlace",
    "scaleInPlace",
    "norm",
    "trace",
    "determinant",
    "submatrix",
    "clone",
    "toArray",
    "toFlatArray",
    "dot",
  ],
} as const;
